name: "Helm Kubeconform (with schema support)"
description: "Generate manifests with `helm template` and run `kubeconform` on the results"
author: "Shiv Jha-Mathur"
inputs:
  strict:
    description: "Whether to run Kubeconform in strict mode"
    default: "true"
  additionalSchemaPaths:
    description: "Newline-separated list of paths to look for schemas under, including filename template"
    default: ""
  chartsDirectory:
    description: "Directory to search for chart directories under"
    default: "charts"
    required: true
  k8sVersion:
    description: "Specify the version of k8s to validated in Kubeconform"
    default: "master"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    # ${{ github }} and (obviously) ${{ env }} aren’t available here, so it isn’t possible to
    # specify a path relative to ${{ github.workspace }} or $GITHUB_WORKSPACE, but
    # `actions/checkout` will just use the current directory, which the runner will point the Docker
    # container at as well, and the Go code will resolve paths against that base directory
    KUBECONFORM_STRICT: "${{ inputs.strict }}"
    ADDITIONAL_SCHEMA_PATHS: "${{ inputs.additionalSchemaPaths }}"
    CHARTS_DIRECTORY: "${{ inputs.chartsDirectory }}"
    HELM_UPDATE_DEPENDENCIES: "true"
    K8S_VERSION: "${{ inputs.k8sVersion }}"
  args: []
